package org.javerland.dataanonymizer;

import picocli.CommandLine.IVersionProvider;

/**
 * Reads the application version from the JAR manifest generated by Maven.
 */
public final class BuildVersionProvider implements IVersionProvider {

    @Override
    public String[] getVersion() {
        String version = BuildVersionProvider.class.getPackage().getImplementationVersion();
        return new String[] { "data-anonymizer " + (version != null ? version : "development") };
    }
}
